---
name: CI / Check and label

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  title:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: doomspork/actions-conventional-commits@latest
        with:
          include-pull-request-title: true
          allowed-commit-types: "fix,feat,chore,docs,refactor"