---
name: CI / Check and label

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  title:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: doomspork/actions-conventional-commits@latest
        with:
          include-pull-request-title: true
          allowed-commit-types: "fix,feat,chore,docs,refactor"

  assign-labels:
    name: Assign labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore']
                labels: ['chore']
              - type: 'docs'
                nouns: ['DOCS', 'Docs', 'docs']
                labels: ['documentation']